SRC = push_swap.c  push_utils.c rotate_utils.c swap_utils.c algo.c algo_utils.c calculs.c cases.c sort.c
LIBFT= ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_is_lower.c ft_is_upper.c ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_memcmp.c ft_strlcpy.c ft_strlcat.c \
    ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c \
    ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putnbr_base.c ft_putaddr.c ft_printf.c ft_putstr_len.c ft_putstr_free.c ft_sizetoa.c ft_ustoa.c ft_itoa_ns.c ft_nblen.c

CLIBFT = $(addprefix libft/, $(LIBFT))
CC = gcc

CFLAGS = -Wall -Wextra -Werror

OBJ = $(SRC:.c=.o) $(CLIBFT:.c=.o)

NAME = push_swap

RM = rm -f

all:		$(NAME)

$(NAME): 	$(OBJ)

clean:
			$(RM) $(OBJ)

fclean:		clean
			$(RM) $(NAME)

re:			fclean $(NAME)

.PHONY:		all clean fclean re
